import type { FieldDefinition, KnowledgeTemplate } from "./types";

const now = "2026-06-06T00:00:00.000Z";

const parameterFields = (): FieldDefinition[] => [
  {
    id: "name",
    label: "名称",
    type: "text",
    required: true,
    placeholder: "target",
  },
  {
    id: "namespace",
    label: "命名空间",
    type: "text",
    required: true,
    placeholder: "Game/Battle/Attack",
  },
  {
    id: "tags",
    label: "标签",
    type: "tags",
    required: false,
    placeholder: "近战, 单体",
  },
  {
    id: "inputs",
    label: "输入参数",
    type: "parameterTable",
    required: false,
  },
  {
    id: "outputs",
    label: "输出参数",
    type: "parameterTable",
    required: false,
  },
  {
    id: "description",
    label: "说明",
    type: "markdown",
    required: false,
    placeholder: "描述使用场景、行为和注意点。",
  },
  {
    id: "example",
    label: "示例",
    type: "markdown",
    required: false,
    placeholder: "写一个典型用法。",
  },
  {
    id: "notes",
    label: "注意事项",
    type: "markdown",
    required: false,
    placeholder: "写边界情况或限制。",
  },
];

export const defaultTemplates: KnowledgeTemplate[] = [
  {
    id: "tile",
    name: "瓦片",
    description: "游戏瓦片、行为瓦片和可配置瓦片的结构化资料。",
    icon: "Grid3x3",
    color: "#0f7c80",
    fields: parameterFields(),
    markdownTemplate: [
      "# {{name}}",
      "",
      "瓦片名称：{{name}}",
      "",
      "命名空间：{{namespace}}",
      "",
      "标签：{{tags}}",
      "",
      "## 输入参数",
      "",
      "{{inputs}}",
      "",
      "## 输出参数",
      "",
      "{{outputs}}",
      "",
      "## 说明",
      "",
      "{{description}}",
      "",
      "## 示例",
      "",
      "{{example}}",
      "",
      "## 注意事项",
      "",
      "{{notes}}",
    ].join("\n"),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "visual-method",
    name: "可视化方法",
    description: "可视化方法代码块、参数、返回值和示例。",
    icon: "Code2",
    color: "#3769a6",
    fields: [
      {
        id: "displayName",
        label: "显示名称",
        type: "text",
        required: true,
        placeholder: "创建全局列表",
      },
      {
        id: "methodName",
        label: "方法名",
        type: "text",
        required: true,
        placeholder: "BuildInFunction_Data_GlobalList_Create",
      },
      {
        id: "tags",
        label: "标签",
        type: "tags",
        required: false,
        placeholder: "列表, 数据",
      },
      {
        id: "parameters",
        label: "参数",
        type: "parameterTable",
        required: false,
      },
      {
        id: "returns",
        label: "返回值",
        type: "parameterTable",
        required: false,
      },
      {
        id: "description",
        label: "说明",
        type: "markdown",
        required: false,
      },
      {
        id: "example",
        label: "示例",
        type: "markdown",
        required: false,
      },
      {
        id: "faq",
        label: "常见问题",
        type: "markdown",
        required: false,
      },
    ],
    markdownTemplate: [
      "# {{displayName}}",
      "",
      "方法名：{{methodName}}",
      "",
      "标签：{{tags}}",
      "",
      "## 参数",
      "",
      "{{parameters}}",
      "",
      "## 返回值",
      "",
      "{{returns}}",
      "",
      "## 说明",
      "",
      "{{description}}",
      "",
      "## 示例",
      "",
      "{{example}}",
      "",
      "## 常见问题",
      "",
      "{{faq}}",
    ].join("\n"),
    createdAt: now,
    updatedAt: now,
  },
];
